apiVersion: v1
kind: Service
metadata:
  name: crra-service
  namespace: crra-dev
spec:
  type: ClusterIP
  selector:
    app: crra
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
